// <auto-generated />
using System;
using Gartengeist.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gartengeist.Api.Migrations
{
    [DbContext(typeof(GartengeistDbContext))]
    [Migration("20260926140923_Journal")]
    partial class Journal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gartengeist.Api.Models.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("beschreibung");

                    b.Property<decimal?>("Length")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("laenge_m");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("typ");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("Width")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("breite_m");

                    b.HasKey("Id");

                    b.ToTable("flaeche");
                });

            modelBuilder.Entity("Gartengeist.Api.Models.Entities.Garden", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("HouseholdSize")
                        .HasColumnType("integer")
                        .HasColumnName("haushaltsgroesse");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("lat");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("standort_name");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("lng");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("plz");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("garten");
                });

            modelBuilder.Entity("Gartengeist.Api.Models.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("menge");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("flaeche_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("datum");

                    b.Property<Guid?>("PlantingId")
                        .HasColumnType("uuid")
                        .HasColumnName("bepflanzung_id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("typ");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("einheit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("nutzer_id");

                    b.Property<int?>("WeatherCode")
                        .HasColumnType("integer")
                        .HasColumnName("wetter_code");

                    b.Property<decimal?>("WeatherPrecipitationMm")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("wetter_niederschlag_mm");

                    b.Property<decimal?>("WeatherTempMax")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("wetter_temp_max");

                    b.Property<decimal?>("WeatherTempMin")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("wetter_temp_min");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("PlantingId");

                    b.HasIndex("UserId");

                    b.HasIndex("AreaId", "Type", "Date");

                    b.ToTable("tagebuch_eintrag");
                });

            modelBuilder.Entity("Gartengeist.Api.Models.Entities.JournalPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("eintrag_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dateiname");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("tagebuch_foto");
                });

            modelBuilder.Entity("Gartengeist.Api.Models.Entities.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("BadCompanions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("mischkultur_schlecht");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kategorie");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DaysToHarvest")
                        .HasColumnType("integer")
                        .HasColumnName("tage_bis_ernte");

                    b.Property<int?>("DirectSowingFrom")
                        .HasColumnType("integer")
                        .HasColumnName("direktsaat_von");

                    b.Property<int?>("DirectSowingTo")
                        .HasColumnType("integer")
                        .HasColumnName("direktsaat_bis");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("familie");

                    b.Property<bool>("FrostSensitive")
                        .HasColumnType("boolean")
                        .HasColumnName("frostempfindlich");

                    b.PrimitiveCollection<string[]>("GoodCompanions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("mischkultur_gut");

                    b.Property<int?>("HarvestFrom")
                        .HasColumnType("integer")
                        .HasColumnName("ernte_von");

                    b.Property<int?>("HarvestTo")
                        .HasColumnType("integer")
                        .HasColumnName("ernte_bis");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schluessel");

                    b.Property<string>("LatinName")
                        .HasColumnType("text")
                        .HasColumnName("lateinisch");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("hinweis");

                    b.Property<string>("NutrientDemand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("naehrstoffbedarf");

                    b.Property<bool>("Perennial")
                        .HasColumnType("boolean")
                        .HasColumnName("mehrjaehrig");

                    b.Property<int?>("PlantSpacingCm")
                        .HasColumnType("integer")
                        .HasColumnName("pflanzabstand_cm");

                    b.Property<int?>("PlantingOutFrom")
                        .HasColumnType("integer")
                        .HasColumnName("auspflanzen_von");

                    b.Property<int?>("PlantingOutTo")
                        .HasColumnType("integer")
                        .HasColumnName("auspflanzen_bis");

                    b.Property<int?>("PreCultivationFrom")
                        .HasColumnType("integer")
                        .HasColumnName("voranzucht_von");

                    b.Property<int?>("PreCultivationTo")
                        .HasColumnType("integer")
                        .HasColumnName("voranzucht_bis");

                    b.Property<int?>("PreCultivationWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("voranzucht_wochen");

                    b.Property<int?>("RowSpacingCm")
                        .HasColumnType("integer")
                        .HasColumnName("reihenabstand_cm");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WaterDemand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wasserbedarf");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("pflanze");
                });

            modelBuilder.Entity("Gartengeist.Api.Models.Entities.Planting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("flaeche_id");

                    b.Property<int?>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("anzahl");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("angelegt_von");

                    b.Property<DateOnly?>("EndedOn")
                        .HasColumnType("date")
                        .HasColumnName("beendet_am");

                    b.Property<DateOnly?>("ExpectedHarvest")
                        .HasColumnType("date")
                        .HasColumnName("voraussichtliche_ernte");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notizen");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("pflanze_id");

                    b.Property<DateOnly?>("PlantingDate")
                        .HasColumnType("date")
                        .HasColumnName("pflanz_datum");

                    b.Property<DateOnly?>("SowingDate")
                        .HasColumnType("date")
                        .HasColumnName("aussaat_datum");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Variety")
                        .HasColumnType("text")
                        .HasColumnName("sorte");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PlantId");

                    b.HasIndex("AreaId", "EndedOn");

                    b.ToTable("bepflanzung");
                });

            modelBuilder.Entity("Gartengeist.Api.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("farbe");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("nutzer");
                });

            modelBuilder.Entity("Gartengeist.Api.Models.Entities.JournalEntry", b =>
                {
                    b.HasOne("Gartengeist.Api.Models.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Gartengeist.Api.Models.Entities.Planting", "Planting")
                        .WithMany()
                        .HasForeignKey("PlantingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Gartengeist.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Planting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gartengeist.Api.Models.Entities.JournalPhoto", b =>
                {
                    b.HasOne("Gartengeist.Api.Models.Entities.JournalEntry", null)
                        .WithMany("Photos")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gartengeist.Api.Models.Entities.Planting", b =>
                {
                    b.HasOne("Gartengeist.Api.Models.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gartengeist.Api.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gartengeist.Api.Models.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("CreatedBy");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Gartengeist.Api.Models.Entities.JournalEntry", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
